CREATE SCHEMA IF NOT EXISTS OWNER_SCHEMA;
CREATE SCHEMA IF NOT EXISTS BLOG_SCHEMA;
CREATE SCHEMA IF NOT EXISTS STUDENT_SCHEMA;



--create if not exists table STUDENT_SCHEMA.STUDENT (
--       ID bigint generated by default as identity,
--        BLOG_DATE timestamp(6),
--        BLOG_DURATION interval second(18,9),
--        BLOG_INSTANT timestamp(6) with time zone,
--        BLOG_LOCAL_DATE date,
--        BLOG_LOCAL_DATE_TIME timestamp(6),
--        BLOG_LOCAL_TIME time,
--        BLOG_OFFSET_DATE_TIME timestamp(6),
--        BLOG_PERIOD varbinary(255),
--        BLOG_SQL_DATE date,
--        BLOG_SQL_TIME time,
--        BLOG_SQL_TIMESTAMP timestamp(6),
--        BLOG_ZONED_DATE_TIME timestamp(6),
--        category varchar(255),
--        content varchar(255),
--        title varchar(255),
--        primary key (ID)
--    );